server:
  port: 8085

spring:
  application:
    name: ai-service
  
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:pulse_ai_db}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Spring AI (Google GenAI Gemini) Configuration
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:AQ.Ab8RN6KlN_u4eiOgO1nLieF4SrTbhnfEfO76q7rZtQ1HGnMyDg}
        chat:
          options:
            model: gemini-2.5-flash

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

# Custom properties for notification topic
app:
  kafka:
    notification-topic: ${NOTIFICATION_TOPIC:notification-topic}


# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://172.23.158.29:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Spring Doc / Swagger OpenAPI UI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
