import React, { useEffect, useState } from 'react';
import { Box, Card, CardContent, Typography, Button, Chip } from '@mui/material';
import { AutoAwesomeOutlined, CheckCircleOutlined, CancelOutlined } from '@mui/icons-material';
import { useSelector, useDispatch } from 'react-redux';
import { toast } from 'react-toastify';
import { setDrafts, approveDraft } from '../store/surveySlice';
import { addNotification } from '../store/notificationSlice';
import { MOCK_DRAFTS } from '../data/dummyData';
import { api } from '../services/api';

const CATEGORY_COLORS = { 'Work-Life Balance': '#00D9A6', Growth: '#FFB547', Leadership: '#63B3ED', Compensation: '#FF6B6B', Collaboration: '#6C63FF' };

export default function DraftsPage() {
  const dispatch = useDispatch();
  const drafts = useSelector((s) => s.survey.drafts || []);
  const [rejected, setRejected] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadDrafts = async () => {
      try {
        const backendDrafts = await api.getDraftQuestions();
        if (backendDrafts && backendDrafts.length > 0) {
          dispatch(setDrafts(backendDrafts));
          setLoading(false);
          return;
        }
      } catch (err) {
        console.warn("Failed to fetch drafts from backend. Using dummy drafts fallback.", err.message);
      }
      
      // Fallback
      if (drafts.length === 0) {
        dispatch(setDrafts(MOCK_DRAFTS));
      }
      setLoading(false);
    };

    loadDrafts();
  }, []);

  const handleApprove = async (draft) => {
    try {
      await api.approveDraft(draft.id);
      dispatch(approveDraft(draft.id));
      dispatch(addNotification({
        id: `N-${Date.now()}`,
        recipient: 'HR',
        subject: 'Draft Approved',
        message: `Question "${draft.text.substring(0, 50)}..." approved and added to the Global Question Bank.`,
        timestamp: new Date().toISOString()
      }));
      toast.success('Question approved and added to next month\'s survey! ✅');
    } catch (err) {
      console.warn("Backend draft approval failed. Doing local fallback...", err.message);
      // Fallback
      dispatch(approveDraft(draft.id));
      toast.success('Question approved (local fallback mode) ✅');
    }
  };

  const handleReject = async (draft) => {
    try {
      await api.rejectDraft(draft.id);
      setRejected([...rejected, draft.id]);
      toast.info('Draft question rejected on backend');
    } catch (err) {
      console.warn("Backend draft rejection failed. Doing local fallback...", err.message);
      setRejected([...rejected, draft.id]);
      toast.info('Draft question rejected');
    }
  };

  const visibleDrafts = drafts.filter(d => !rejected.includes(d.id));
  const approvedCount = visibleDrafts.filter(d => d.approved || d.status === 'APPROVED').length;

  return (
    <Box sx={{ maxWidth: 900, mx: 'auto' }}>
      <Box className="fade-in-up" sx={{ mb: 4 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 1 }}>
          <AutoAwesomeOutlined sx={{ color: '#FFB547', fontSize: 28 }} />
          <Typography variant="h5" sx={{ fontWeight: 700 }}>AI-Generated Draft Questions</Typography>
        </Box>
        <Typography variant="body2" sx={{ color: '#94A3B8' }}>These questions were generated by our AI Sentiment Engine based on last month's employee feedback analysis. Review, approve, or reject them before they go live.</Typography>
      </Box>

      {visibleDrafts.map((draft, i) => {
        const isApproved = draft.approved || draft.status === 'APPROVED';
        return (
          <Card key={draft.id} className="fade-in-up" sx={{ mb: 2, animationDelay: `${i * 100}ms`, borderLeft: `3px solid ${CATEGORY_COLORS[draft.category] || '#6C63FF'}` }}>
            <CardContent sx={{ p: 3 }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 2 }}>
                <Box sx={{ flex: 1, minWidth: 300 }}>
                  <Typography variant="h6" sx={{ fontWeight: 600, mb: 1.5, lineHeight: 1.5 }}>{draft.text || draft.questionText}</Typography>
                  <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                    <Chip label={draft.category} size="small" sx={{ bgcolor: `${CATEGORY_COLORS[draft.category] || '#6C63FF'}20`, color: CATEGORY_COLORS[draft.category] || '#6C63FF' }} />
                    {draft.themeTag && <Chip label={draft.themeTag} size="small" variant="outlined" sx={{ borderColor: 'rgba(255,255,255,0.12)' }} />}
                    {isApproved ? <Chip icon={<CheckCircleOutlined />} label="Approved" size="small" sx={{ bgcolor: 'rgba(0,217,166,0.15)', color: '#00D9A6' }} />
                      : <Chip label="Pending Review" size="small" sx={{ bgcolor: 'rgba(255,181,71,0.15)', color: '#FFB547' }} />}
                  </Box>
                </Box>
                {!isApproved && (
                  <Box sx={{ display: 'flex', gap: 1 }}>
                    <Button variant="contained" size="small" startIcon={<CheckCircleOutlined />} onClick={() => handleApprove(draft)}
                      sx={{ bgcolor: '#00D9A6', color: '#0A0E1A', '&:hover': { bgcolor: '#00B88A' } }}>Approve</Button>
                    <Button variant="outlined" size="small" startIcon={<CancelOutlined />} onClick={() => handleReject(draft)}
                      sx={{ borderColor: '#FF6B6B', color: '#FF6B6B', '&:hover': { bgcolor: 'rgba(255,107,107,0.08)' } }}>Reject</Button>
                  </Box>
                )}
              </Box>
            </CardContent>
          </Card>
        );
      })}

      <Card className="fade-in-up" sx={{ mt: 3, background: 'rgba(108,99,255,0.06)', border: '1px solid rgba(108,99,255,0.15)' }}>
        <CardContent sx={{ p: 2, display: 'flex', justifyContent: 'center', gap: 3 }}>
          <Typography variant="body2" sx={{ color: '#94A3B8' }}>Approved: <strong style={{ color: '#00D9A6' }}>{approvedCount}</strong></Typography>
          <Typography variant="body2" sx={{ color: '#94A3B8' }}>Total Visible: <strong style={{ color: '#F1F5F9' }}>{visibleDrafts.length}</strong></Typography>
          <Typography variant="body2" sx={{ color: '#94A3B8' }}>Rejected: <strong style={{ color: '#FF6B6B' }}>{rejected.length}</strong></Typography>
        </CardContent>
      </Card>
    </Box>
  );
}
