server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jwt:
  secret: MySecretKeyForInventoryManagementSystem2024!VeryLongAndSecure

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


management:
  tracing:
    sampling:
      probability: 1.0 # Capture 100% of requests (use lower, e.g., 0.1, for production)
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans" # Replace with your Zipkin URL



